name: paulo-at-root-workflow

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  my_job_at_root:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Run on one-line script
        run: echo Hello world at root!!!

      - name: Run on multi-line script
        run: |
          echo my first multi-line echo at root
          echo my second multi-line echo at root
          echo my third multi-line echo at root
