name: paulo-manual-workflow

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-lastest
  
    steps:
      - uses: actions/checkout@v3

      - name: Run on one-line script
        run: echo Hello world!!!

      - name: Run on multi-line script
        run: |
          echo hello world!!!
