name: paulo-third-workflow

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Run on one-line script
        run: echo Hello world!!!

      - name: Run on multi-line script
        run: |
          echo my first multi-line echo in third workflow
          echo my second multi-line echo in third workflow
          echo my third multi-line echo in third workflow
